FROM pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    gcc \
    && apt-get clean \
    && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir \
    matplotlib \
    numpy \
    optuna \
    pandas \
    pickle5 \
    pymatgen \
    sklearn \
    tqdm

ENTRYPOINT ["python"]
