FROM pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    gcc \
    && apt-get clean \
    && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
RUN pip3 install --upgrade pip
COPY requirements.txt /tmp/
RUN pip3 install --no-cache-dir --requirement /tmp/requirements.txt

ENTRYPOINT ["python"]
