name: DockerHub

# Controls when the workflow will run
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-gpu:
    strategy:
      matrix:
        pytorch-version: [1.13.1]
        cuda-version: [11.6]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta-gpu
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/ml-env
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
            prefix=
            suffix=-torch${{ matrix.pytorch-version }}-cuda${{ matrix.cuda-version }}-gpu,onlatest=false
      - uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            PYTORCH_VERSION=${{ matrix.pytorch-version }}
            CUDA_VERSION=${{ matrix.cuda-version }}
          push: true
          file: ./Dockerfile.gpu
          tags: ${{ steps.meta-gpu.outputs.tags }}
          labels: ${{ steps.meta-gpu.outputs.labels }}
  build-cpu:
    strategy:
      matrix:
        pytorch-version: [1.13.1]
        miniconda-version: [22.11.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta-cpu
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/ml-env
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
            prefix=
            suffix=-torch${{ matrix.pytorch-version }}-miniconda${{ matrix.miniconda-version }}-cpu,onlatest=true
      - uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            PYTORCH_VERSION=${{ matrix.pytorch-version }}
            MINICONDA_VERSION=${{ matrix.miniconda-version }}
          push: true
          file: ./Dockerfile.cpu
          tags: ${{ steps.meta-cpu.outputs.tags }}
          labels: ${{ steps.meta-cpu.outputs.labels }}
