name: GitHub Container Registry

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-gpu:
    strategy:
      matrix:
        pytorch-version: [1.13.1]
        cuda-version: [11.6]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta-gpu
        with:
          images: ghcr.io/${{ github.actor }}/ml-env
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
            prefix=
            suffix=-torch${{ matrix.pytorch-version }}-cuda${{ matrix.cuda-version }}-gpu,onlatest=false
      - uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            PYTORCH_VERSION=${{ matrix.pytorch-version }}
            CUDA_VERSION=${{ matrix.cuda-version }}
          push: true
          file: ./Dockerfile.gpu
          tags: ${{ steps.meta-gpu.outputs.tags }}
          labels: ${{ steps.meta-gpu.outputs.labels }}
  build-cpu:
    strategy:
      matrix:
        pytorch-version: [1.13.1]
        miniconda-version: [22.11.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta-cpu
        with:
          images: ghcr.io/${{ github.actor }}/ml-env
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
            prefix=
            suffix=-torch${{ matrix.pytorch-version }}-miniconda${{ matrix.miniconda-version }}-cpu,onlatest=true
      - uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            PYTORCH_VERSION=${{ matrix.pytorch-version }}
            MINICONDA_VERSION=${{ matrix.miniconda-version }}
          push: true
          file: ./Dockerfile.cpu
          tags: ${{ steps.meta-cpu.outputs.tags }}
          labels: ${{ steps.meta-cpu.outputs.labels }}
